language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
# command to install dependencies
install:
  - pip install pytz
  - pip install zeep
  - pip install coverage
  - pip install coveralls
# command to run tests
script: nosetests --logging-level=INFO --with-coverage --cover-tests --cover-package=thepay
after_success: coveralls
